### ISSUE TITLE
Where is chiphunk-example?

### ISSUE THREAD

**Issue by lemmih** [CthulhuDen/chiphunk#2]
I can't find that package anywhere.

**Comment by CthulhuDen** [comment]
So I've brought back example as executable in this package which is not built by default (you can run it with `stack run` or disable `library-only` flag if you use cabal). For me it required to install libglu-dev and libglew-dev (Ubuntu).

Source: https://github.com/CthulhuDen/chiphunk/blob/master/app/Main.hs
